# Generated by Django 3.0.3 on 2020-03-03 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('pwd', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
                ('creatTime', models.DateTimeField(auto_now_add=True)),
                ('userToken', models.CharField(max_length=50)),
                ('sign', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ptype', models.CharField(max_length=2)),
                ('num', models.IntegerField()),
                ('content', models.CharField(max_length=150)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.CharField(default='media/img/default.png', max_length=100)),
                ('creatTime', models.DateTimeField(auto_now_add=True)),
                ('usedTime', models.DateTimeField(null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('isUsed', models.BooleanField(default=False)),
                ('puser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myLucky.User')),
            ],
            options={
                'db_table': 'prize',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Attach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachTime', models.DateTimeField(auto_now_add=True)),
                ('isLucky', models.BooleanField(blank=True, null=True)),
                ('attachPrize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myLucky.Prize')),
                ('attachUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myLucky.User')),
            ],
            options={
                'db_table': 'attach',
                'ordering': ['id'],
            },
        ),
    ]
